### ISSUE TITLE
Limit Que // Limit number of songs by user

### ISSUE THREAD

**Issue by AxiomInfinite** [snowelie/orin#12]
Limit Que to 10 songs // prevent song spam by single user-  limit to 2 max per user on song list

**Comment by snowelie** [comment]
Should this be limited per queue or per time interval? Can add 2 songs per queue, max? Or 2 songs every 10 minutes? 

Limiting per queue I think introduces some problems such as: 

- the queue is about to end but I can't add songs anymore because I've reached the limit. Do I leave the queue to die and then add my song, getting limited again?
